import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/darklogo.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer
          style={{
            width: '100vw',
            background: '#23272e',
            color: '#888',
            textAlign: 'center',
            fontSize: '0.95rem',
            padding: '1.2rem 0',
            borderTop: '1px solid #22262c',
            position: 'fixed',
            left: 0,
            bottom: 0,
            zIndex: 1000,
          }}
        >
          Note: Currently, this tool only supports bitstream generation for <b>Lattice iCE40 FPGAs</b>.
        </footer>
      </body>
    </html>
  );
}
